models:
    MLPClassifier:
        param:
            random_state: 0
            hidden_layer_sizes: 4
            activation: |
                "relu"
            max_iter: 1000
            batch_size: 256
            learning_rate_init: 0.01
        shap: True
        save: True
        shap_type: shap.Explainer

    XGBClassifier:
        param:
            random_state: 0
            booster: |
                "gbtree"
            learning_rate: 0.1
            max_depth: 1
            n_estimators: 500
            gamma: 1
            min_child_weight: 5
            colsample_bytree: 0.7
            objective: |
                "binary:logistic"
        shap: True
        save: True
        shap_type: shap.Explainer   
              
scoring_train:
    
    precision:
        class: precision_score
        param:
            y_true: y_train
            y_pred: y_pred_train
            pos_label: 1
            
    NPV:
        class: precision_score
        param:
            y_true: y_train
            y_pred: y_pred_train
            pos_label: 0
                
    roc_auc:
        class: roc_auc_score
        param:
            y_true: y_train
            y_score: y_proba_train

            
scoring_test:
    
    precision:
        class: precision_score
        param:
            y_true: y_test
            y_pred: y_pred_test
            pos_label: 1
            
    NPV:
        class: precision_score
        param:
            y_true: y_test
            y_pred: y_pred_test
            pos_label: 0
            
    roc_auc:
        class: roc_auc_score
        param:
            y_true: y_test
            y_score: y_proba_test            
            

numerical features:
    - age
    - bmi
    - nrsheadache
    - nrsneck
    - nrsarm
    - ndi
    - eq5d
    - eqvas
    - prevsurg
    - asa

clusters:
    Fold 1: 1
    Fold 2: 2
    Fold 3: 3
    Fold 4: 4
    Fold 5: 5
    